---
title: "276 Project"
author: "Ron Kinel, Rebecca He, Lingyu Zhou, Wenjing Li, Samran Khan"
date: "5/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Problem 1

```{r p1}
StockVol <- function(histoPrice){

  R <- array(0 , length(histoPrice)-1)
  
  for (i in 1:(length(R))){
    R[i] <- log(histoPrice[i+1]/histoPrice[i])
  }
  
  Daily_vol <- sqrt(var(R))
  
  
  Annual_Vol <- Daily_vol*sqrt(252)
  
  return(Annual_Vol)
}



Prices <- read.csv(file = 'C:/Users/ron12/OneDrive/Desktop/PSTAT 276/IBM-MSFT-HAS.csv', 
                   header = T, sep = ",")

StockVol(Prices$IBM)

```


# Problem 2

```{r p2}
#n: number of paths
#sigma: volatilty/variance of stock, not sd
#S0: current stock price
#t: terminal time in yearly unit
#np: number of periods
#r: interest rate
#delta: continuous dividend yield of the stock

StockPath <- function(n, sigma, S0, t, np=t, r, delta=0){
  S <- array(0, dim=c(n,np+1))
  S[,1] <- S0
  Z <- matrix( rnorm(n*(np)), n, (np))
  h <- t/np 
  #h: length of each period = t/np
  
  for(i in 1:n){
    for (j in 1:np) {
      S[i,j+1] <- S[i,j]*exp((r-delta-(sigma^2)/2)*h + sqrt(h*(sigma^2))*Z[i,j])
    }
  }
  
  mypath <- S
  return(mypath)
}

StockPath(20,.2,50,1,12,.04,0)

```


# Problem 3

```{r p3}
set.seed(20)

EurOptPrice <- function(n, sigma=histoVol, S0, t, np=t, r, delta=0, k=S0){
  mypath <- StockPath(n, sigma, S0, t, np, r, delta) #updates "mypath" from problem 2 with new values.
  
  disc_payoff <- array(0, dim=c(n,1)) #discounted payoff vector
  
  for (i in 1:n){
    disc_payoff[i,1] <- exp(-r*t)*pmax(k-mypath[i,(np+1)] ,0)
  }
  
  option_price <- mean(disc_payoff)
  option_var <- var(disc_payoff)
  
   return(list( disc_payoff , option_price, option_var))
}

A <- EurOptPrice(20,.04,50,10,5,.04,0,50)

A
A[[1]]
A[[2]]
A[[3]]
```

#Problem 4

```{r p4}

```

#Problem 5

```{r p5}
ContVariate <- function(n, Unknown_Vec, Known_Payoff, Known_Price, Known_Var){
  #check that vectors are correct
  Y <- Unknown_Vec[sample(1:length(Unknown_Vec), n)]
  
  
  
  
  
}

```



